<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Banner Description</label>
    <textarea rows="4" cols="50" class="form-control" id="exampleInputEmail1" placeholder="Banner Description"></textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>