<style type="text/css">
	table{
		border:1px solid black;
	}
	td{
		padding: 10px;
		border:1px solid black;
	}
	#showMap{
		width: 150px;
		height: 150px;
	}
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript">
 $(document).ready(function(){
 	$("#showMap").hide();
 	$("#city").change(function(){
 		$("#showMap").hide();
 		var city = $("#city").val();
 		if(city=='')
 		{
 			window.location.href="http://localhost/magento/index.php/locatore";
 		}
 		else
 		{
	 		 $.ajax({
	 		 	url: "http://localhost/magento/index.php/locatore/index/select",
	 		 	type:"post",
	 		 	data:"city="+city,
	 		 	 success: function(result)
	 		 	 	{
	       			 	$("#dataContent").html(result);
	       			 	
	    			}

				});
 		 }
 	})
 })
</script>
<script type="text/javascript">
function show_map(id)
{
	$("#showMap").show();
	$.ajax({
 		 	url: "http://localhost/magento/index.php/locatore/index/showmap",
 		 	type:"post",
 		 	data:"id="+id,
 		 	 success: function(result)
 		 	 	{
       			 	$("#showMap").html(result);
       			 	//alert(result);
       			 	
    			}

			});
}
</script>
<?php 
  $data=$this->getOwnerName();
?>
<table>
	<tr>
		<td>Id</td>
		<td>Store Name</td>
		<td>Store City</td>
		<td>Store Address</td>
	</tr>
<?php
foreach ($data as $value)
 {
	?>
	<tr>
		<td><?php echo $value['id'];?></td>
		<td><?php echo $value['store_name'];?></td>
		<td><?php echo $value['city'];?></td>
		<td><?php echo $value['store_address'];?></td>
	</tr>
<?php
 }
?>
</table>
<br>
<?php 
foreach($data as $val)
{
	$city_arr[]=$val['city'];
}
$city=array_unique($city_arr);
?>
<select name="city" id="city">
	<option value="">Select City</option>
		<?php foreach($city as $city_value) 
		{
		?>
			<option value="<?php echo $city_value;?>"><?php echo $city_value;?></option>
		<?php
		 } 
		 ?>
</select>
<div id="dataContent">
</div>
<div id="showMap">
</div>
