<style type="text/css">
.product{
	overflow: hidden;
	width:50%;
}
.productInfo{
	float:left;
	width:30%;
	height:30%;
	border: 1px solid black;
	margin-right:3%;
}
.ProductImage{
	float:left;
	width:100%;
	height:80%;
	border: 1px groove black
}

.ProductImage img{
	float:left;
	width:100%;
	height:80%;
	border: 1px groove black;
	cursor: pointer;
}
.ProductName{
	float:left;
	width:100%;
	height:20%;
	cursor: pointer;
	
}
</style>
<div class = 'product'>
	<?php
	$_productCollection = $this->getProductCollection();
	foreach($_productCollection as $_productData) {
	?>
	<div class = "productInfo">
		<div class = "ProductImage">
			<img src = "<?php echo $_productData->getImageUrl() ; ?>">
		</div>
		<div class = "ProductName">
			<?php echo $_productData->getName(); ?>
		</div>
	</div> 
	<?php	
	}
	?>
</div>
